[package]
name = "stripe-orders"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-stripe-common = { path = "../../async_stripe_common" }
async-stripe-core = { path = "../../async_stripe_core" }
